### ISSUE TITLE
When Project View is open AceJump fails to find some matches

### ISSUE THREAD

**Issue by amandle** [acejump/AceJump#168]
When the project view (directory tree) is open, AceJump fails to find some matches.  Closing the project view causes AceJump to find all matches.

With Project View open:
![screen shot 2017-07-12 at 1 18 25 pm](https://user-images.githubusercontent.com/879468/28138357-68858956-6705-11e7-8433-6ad9b72a69e8.png)

With Project View closed:
![screen shot 2017-07-12 at 1 23 13 pm](https://user-images.githubusercontent.com/879468/28138371-6eedc164-6705-11e7-8a76-95e6da243ebd.png)

PyCharm 2017.1.5
AceJump 3.3.4

**Comment by breandan** [comment]
Most likely related to #166, #167. Will investigate, thanks for reporting.

**Comment by amandle** [comment]
A bit more information:
My setup is a very wide monitor with PyCharm maximized

I have from left to right:
Project View | Split 1 | Split 2 | Split3

With the exact same text in each split (see comment 1 above),
split 1 finds all instances, split 2 finds only the first few, split 3 finds none.

I'm not sure that's helpful, but thanks for looking into it, and thanks for a great plugin!

**Comment by breandan** [comment]
I believe this issue has either been fixed, or if not, is somehow related to #71. Please feel free to follow that issue instead.
