### ISSUE TITLE
AceJump stops working when I move a tab to an editor group

### ISSUE THREAD

**Issue by arvinsim** [acejump/AceJump#178]
On load, AceJump works perfectly on Webstorm. But once I try to split/move a tab, it stops working.

**Comment by jgololicic** [comment]
The same issue here... After restarting the PhpStorm it works again. 

PhpStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017
Subscription is active until February 16, 2018
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

**Comment by breandan** [comment]
I believe this issue is somehow related to #71. Please feel free to follow that issue instead.
