### ISSUE TITLE
AceJump stops working after ctrl + tab in Distraction Free Mode

### ISSUE THREAD

**Issue by yannick-cw** [acejump/AceJump#181]
Hey I am running acejump in
* Intellij 2017.2.1
* Mac OSX 10.12.6

Currently no matter what language or file, as soon as I hit `ctrl + tab` to use the Switcher for switching between files, AceJump stops working.

This seems to only happen reproducable in distraction free mode.

Starts to work again after restarting.

**Comment by mentorkadriu** [comment]
Same is happening to me too.
PhpStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017

JRE: 1.8.0_152-release-915-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by breandan** [comment]
Was unable to reproduce as of `3.5.8`/`IU-193.4778.7`, if this is still an issue please feel free to reopen.
