### ISSUE TITLE
Add a new feature, search for current line

### ISSUE THREAD

**Issue by ianva** [acejump/AceJump#201]
Most of the time, people always focus on current line when they input something or edit something, Vim’s `f` is not convenient.

AceJump mostly is convenient, I think that it suitable for jump out of current thinking way.

AceJump distracted from work when it was applied, because viewable area of editor was change suddenly, a lot of highlight characters were flash into sight and thinking way was broken.

If it’s able to deal with current line when people working with current line, it will have better experience for user.

[Stupid-EasyMotion](https://github.com/joequery/Stupid-EasyMotion) is a good example.

**Comment by breandan** [comment]
Okay, now I understand. This seems like a good idea, we can add it as a configuration in the settings page. Thanks for the suggestion (and clarifying #114).

**Comment by ianva** [comment]
OK, Are you remember #114?
My english is not that fluent, so I can't statement this feature, Thx.

**Comment by breandan** [comment]
Introduced in AceJump `3.5.0`, AceJump now offers **Word Mode**, which searches the editor screen for matches as proposed in #210. We might consider adding a separate line mode, for only returning matches on the current line. Ultimately, all of these modes should be user-configurable as described in #215.

**Comment by breandan** [comment]
It should be noted that vi already supports line movements [by default](https://hea-www.harvard.edu/~fine/Tech/vi.html) with the <kbd>f</kbd> key.

**Comment by breandan** [comment]
You can now press <kbd>Enter</kbd> to cycle through the nearest visible matches. This makes it easier to select results on the current line, but does not restrict results or reduce visual noise as you mentioned above.

**Comment by breandan** [comment]
There is a [new plugin](https://github.com/AlexPl292/IdeaVim-EasyMotion) for the IntelliJ Platform based on [EasyMotion](https://github.com/easymotion/vim-easymotion) which supports a similar feature, cf. #299.

**Comment by breandan** [comment]
I believe we can close this issue as it is now supported in EasyMotion. Also relates to #299.
