### ISSUE TITLE
Does not display jump letters on right splitted vertically screen

### ISSUE THREAD

**Issue by mgrzaslewicz** [acejump/AceJump#203]
Using ace jump version 3.4.2, 2017.2.5 Build UI-172.4343.14

### Steps to reproduce

- open any java class on the right in vertically split view
- press 'ctrl + ;'
- type one or two letters marking place to jump into

### What's wrong?
Only matching places are shown (as at the screenshot), no keyboard shortcuts to jump are generated
When opened in left view works as expected

Right view broken, typed 'ctrl + ;' then 'co'
![image](https://user-images.githubusercontent.com/5358084/31997613-860e2f06-b984-11e7-8608-abb811e0c76d.png)

Left view OK, typed 'ctrl + ;' then 'co'
![image](https://user-images.githubusercontent.com/5358084/31997625-929f8fda-b984-11e7-9002-1c38d51a96a5.png)

**Comment by pengVc** [comment]
i meet some problem with Webstorm 2017.2.5

Left side is ok, Right side is error, ScreenShot:

**Left**
![image](https://user-images.githubusercontent.com/5656735/32430143-f25a15fc-c308-11e7-9f8e-6b03f5a19abe.png)

**Right**
![image](https://user-images.githubusercontent.com/5656735/32430175-1172a206-c309-11e7-81f1-773b06a8ffea.png)

**Comment by skekec** [comment]
Same here :(

**Comment by ovovchuk** [comment]
Looks like this is the bug in IntelliJ Platform. I have debugged AceJump code base on IntelliJ CE 2017.2.6 and IntelliJ CE 2017.3 EAP and on the last one AceJump works well on both sides.

**Comment by dudunato** [comment]
Same here!

**Comment by minutuslausus** [comment]
+1

**Comment by breandan** [comment]
We've been tracking signs of this bug for some time, still not sure what the culprit is. Related: #71, #178

**Comment by ovovchuk** [comment]
Works fine in IntelliJ Idea 2017.3

**Comment by krevels** [comment]
I can also confirm that this is working in PHPStorm 2017.3

**Comment by hhsadiq** [comment]
+1

Faced this issue PhpStorm 2017.1

**Comment by extempl** [comment]
Not sure this is the right place but is it even planned to do cross-split-files jumps with ace-jump? W/o need in changing active focused file (not really easy when there are three+ files).

**Comment by breandan** [comment]
> is it even planned to do cross-split-files jumps with ace-jump?

@extempl Yes, but this is a different ticket. Please see #144.

**Comment by breandan** [comment]
I believe this issue is probably a duplicate of #71, let's move the discussion there. Thanks.
