### ISSUE TITLE
Add option for displaying tooltip after n-keystrokes

### ISSUE THREAD

**Issue by nhat** [acejump/AceJump#204]
Currently AceJump wait a short time after the last keystroke and then it shows the tooltip for all matching words.

This option would allow users to configure after how many keystroke the tooltip should appears, e.g. he enter 2 characters and AceJump activate the tooltip. The advantage would be more consistency and faster navigation, because the user doesn't have to wait for the delay to expire.

**Comment by breandan** [comment]
Duly noted. The keystroke delay should be a configurable setting. In the meantime, typing two or more characters is usually enough to cause the tooltips to display immediately.

**Comment by breandan** [comment]
AceJump now supports near-instantaneous tagging, by only considering the visible search area. To enable it, open the settings page and select the option to only tag the visible area. Feel free to try the [canary build](https://teamcity.jetbrains.com/repository/download/acejump_buildplugin/.lastSuccessful/AceJump.zip?guest=1) and leave your feedback.
