### ISSUE TITLE
Feature request? Tag letters appear too slow.

### ISSUE THREAD

**Issue by saroff** [acejump/AceJump#207]
Currently after i typed my word and see it higlighted, there is 1-2 seconds delay before tag letter will appear so i can type them in order to jump. Delay is not so big, but still noticable, and makes me wait for it every time. 
It would be nice to be able to configure it with settings.

**Comment by matklad** [comment]
Strong +1 from me! It is extremely annoying that tags appear only after a perceivable delay. I understand that AceJump is very smart and powerful, and can dynamically switch between "jump to spot" and "search in files" modes. It must be the case that a lot users actually need these advanced features, but I, and maybe some other people,  only use "jump to the spot" on the screen feature. For this category of users, it would be very helpful to have a "disable all timeouts and to the simplest thing in the fastest possible way" checkbox :-)

**Comment by matklad** [comment]
Hm, just found https://plugins.jetbrains.com/plugin/9803-acejump-lite, which seems much faster, though not as feature complete :)

**Comment by breandan** [comment]
Thank you for your feedback. We should reach out to the developers of acejump-lite to see if they would be willing to submit their work as a PR (with attribution in the readme). Otherwise, we can  implement "AceJump Lite Mode", where we disable the multi-character search and only use single-character tags to select sites visible in the editor. This would be fairly straightforward to implement.

**Comment by breandan** [comment]
As described in #217, AceJump-Lite style tagging has been implemented by @chylex and should be available in `3.7.0`. To enable it, open the settings page and select the option to only tag the visible area. Feel free to try the [canary build](https://teamcity.jetbrains.com/repository/download/acejump_buildplugin/.lastSuccessful/AceJump.zip?guest=1) and leave your feedback.
