### ISSUE TITLE
Feature request: AceJump + multiple caret

### ISSUE THREAD

**Issue by saroff** [acejump/AceJump#221]
Multiple caret feature in idea really bad when it can't be selected automatically via `alt+j` or by cloning caret above/below. You have to `ctrl + shift + alt` + manually click needed places. It would be great to AceJump to needed word + clone caret.

Suppose i have class like that:

```
import java.util.Collection;
import java.util.List;

public class scratch {
    protected Collection getInputTest() {
        //some code
        return null;
    }
    public List getOutputTest() {
        //some code
        return null;
    }
}
```

I want to add methods like `getInputTestById(String id)`. Really handy will be to copy-paste them, clone caret, and change sigs. With proposed feature it will be really simple. Copy-paste methods, AceJump to "Test", AceJump cloning caret to another test, done. No need to take hands off keyboard. This example is somewhat artificial, but in my daily job there is cases where multiple carets feature will be helpfull, but i can't clone caret using shortcuts.

It can be implemented just by keeping caret, so if you want to place 3 carets, you will need to press `AceJump clone caret` two times. Or like `shortcut` + search for a word + type tag + search persists, you can type another tag or `backspace` to search for another word  + hit `Enter` to place caret in all these places.

**Comment by saroff** [comment]
By the way, right now if i use AceJump having multiple carets, last placed caret will affected.

**Comment by breandan** [comment]
Hmm, this might be a useful addition. We could call it "Multicaret mode", where a new caret is added in addition to the current one(s). However, this could easily be added as a Find-based feature to the IntelliJ Platform. You could also try adding this as a [feature request](https://youtrack.jetbrains.com/issues/IDEA?q=%23%7Bmultiple%20carets%7D%20) on YouTrack.

**Comment by breandan** [comment]
Addendum: IdeaVim does not support multiple carets, although this feature is currently [on the radar](https://youtrack.jetbrains.com/issue/VIM-780#comment=27-2491960).

**Comment by breandan** [comment]
I noticed that IdeaVim's multi-caret selection mode has recently improved. As [discussed here](https://github.com/acejump/AceJump/issues/350#issuecomment-753856650), I am a little hesitant to add features that overlap with IdeaVim functionality, although it may be possible to offer a smoother multi-caret integration. In any case, let's merge this discussion with #350. Thank you for the suggestion!
