### ISSUE TITLE
Why don't labels appear?

### ISSUE THREAD

**Issue by naah69** [acejump/AceJump#224]
![image](https://user-images.githubusercontent.com/25682169/37584327-00a1384e-2b90-11e8-9e31-dd380f113645.png)

**Comment by breandan** [comment]
It is possible that you have not waited long enough for the labels to appear. What IDE and plugin version are you using?

**Comment by naah69** [comment]
i use IDEA 2017.3.2.i wait for a long time ,but i won't appear
![snipaste_20180403_151825](https://user-images.githubusercontent.com/25682169/38235077-7714e57a-3752-11e8-80e5-7ec7c8cfdd69.png)
![snipaste_20180403_151836](https://user-images.githubusercontent.com/25682169/38235088-7c05de72-3752-11e8-9027-da74f28d4ffd.png)

**Comment by breandan** [comment]
Try updating to a more recent version of AceJump and the IntelliJ Platform? I'm not sure what's the issue here, but unable to reproduce. Please feel free to reopen if this occurs on a later version, with a log (**Help | Show Log**). Thanks!
