### ISSUE TITLE
Display current search text

### ISSUE THREAD

**Issue by saroff** [acejump/AceJump#227]
Currently it's not possible to see exact text you are searching for. It can be handy to have small badge in the corner of the editor displaying current search, to see if you mistyped something, for example.

**Comment by breandan** [comment]
This is a good idea and could probably be added as an option. But in general, the text you are searching for will always be highlighted and visible. If the query is not in view, this means it does not exist in the document.

**Comment by oxysoft** [comment]
Hi,I would like to add that this would be a very wise addition for me as well. I understand the want to be minimalist but something like the Incremental Search feature would be perfect. The popup is minimal and appears right above the text editor.

![image](https://user-images.githubusercontent.com/3945277/55445443-6f6ff700-5589-11e9-9fd3-72d898cc0395.png)

This removes a whole layer of ambiguity when searching.

**Comment by breandan** [comment]
This feature should now be available in [`3.8.2`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/119819) and can be enabled by selecting the `Show hint with search text` option in the AceJump settings. Big thanks to @SaiKai for the PR!
