### ISSUE TITLE
Incorrect horizontal tag placement when parameter hints enabled

### ISSUE THREAD

**Issue by saroff** [acejump/AceJump#233]
![image](https://user-images.githubusercontent.com/6500849/39868752-97663d46-5463-11e8-9a86-6d309b3c803d.png)

See screenshot. I can't find any stable repro steps for it though. It always happens for me only in 1 file. I tried creating some stub files with long enough lines, no luck.

**Comment by chylex** [comment]
Similar issue exists with text highlights, for ex. typing `1F` here shows up as:
![obrazek](https://user-images.githubusercontent.com/3685160/100245665-99cdaf80-2f38-11eb-9549-361b4aa126a4.png)

I'm working on a refactor and fixing various issues as I go, so in this example I typed `getter, () ->` and the highlight travels across inlay hints (although it perhaps starts too soon, I'll see if I can improve that):
![obrazek](https://user-images.githubusercontent.com/3685160/100245866-cd103e80-2f38-11eb-82c8-d1cc769e43db.png)

I wasn't actually able to reproduce this with markers in recent versions, only highlights seem broken.

**Comment by breandan** [comment]
Thanks to #353 has now been fixed in [`3.7`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/115735). Feel free to try it out and leave your feedback!
