### ISSUE TITLE
Press `enter` for jump to next doesn't work if the next item is off the current screen

### ISSUE THREAD

**Issue by excetara2** [acejump/AceJump#235]
I just noticed this but it might be the desired behavior that if something is in the document but not on the current screen and you want to jump to the next. When you hit `enter`, it doesn't take you there. Also, even if you use `tab` to cycle to the point so it is on the screen, you still can't press enter once you are there as it seems to take you somewhere random instead of the desired location. 

Also, it seems if that is the only occurrence of that item in the text, when you cycle through and get to the page it is on, then the letters normally in front of it don't seem to be there unless you type another character. This doesn't seem to happen if there is more than one occurrence. Or possibly it's the case if there are occurrences on the first screen when you searched.

**Comment by excetara2** [comment]
Sorry, I posted too early and it seems this is only the issue with text that has `(` as the starting character for the acejump. I was using it to jump to numbered TODOs like `TODO (9)` in a file. So typing `(9` as the jump to text. Sorry about the previous posts as this is the problem more isolated.

**Comment by breandan** [comment]
I believe this should be fixed as of `3.5.8`, otherwise please feel free to reopen.
