### ISSUE TITLE
Different look for the nearest match

### ISSUE THREAD

**Issue by oxysoft** [acejump/AceJump#239]
That way, you know where you'll end up if you press enter! Shouldn't be too hard to implement and would increase usability tenfold!

**Comment by breandan** [comment]
Good idea! Thanks for the suggestion, this would also help to diagnose #235.

**Comment by oxysoft** [comment]
Just noticed this today along with the ability to jump down a few occurences by pressing ENTER repeatedly. It's awesome, thanks!

**Comment by breandan** [comment]
Glad to hear, thanks for replying! It's currently an experimental undocumented feature, but you can cycle through visible tags by pressing `Enter` repeatedly, then press `Esc` to exit. I am considering removing the `Esc` key, so as soon as you type `Enter` followed by a non-`Enter` key, it will immediately exit AceJump and perform that action in the editor. Also, to scroll to the next group of matches, you can always press `Tab` - this seems to work well with the cyclical `Enter` in my experience.
