### ISSUE TITLE
Off-screen results missing tags

### ISSUE THREAD

**Issue by saroff** [acejump/AceJump#245]
How to reproduce: 

1. Create big enough document
2. Search for some string, that exists somewhere in the document, but not on the screen.
3. Press `tab` so that window will be scrolled to next search results.

Expected: search results must have tags as usual
Actual: search results are highlighted, but there is no tags.

Everything works as expected, when there is at least one on-screen result.

**Comment by breandan** [comment]
Thanks for describing the steps to reproduce this issue, this is very helpful.
