### ISSUE TITLE
Found usages are black in latest EAP

### ISSUE THREAD

**Issue by mallowigi** [acejump/AceJump#252]
http://prntscr.com/l5ofqv

IntelliJ IDEA 2018.3 EAP (Ultimate Edition)
Build #IU-183.3647.12, built on October 10, 2018
IntelliJ IDEA EAP User
Expiration date: November 9, 2018
JRE: 1.8.0_152-release-1343-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14

I know it's from this plugin, don't know why though.

**Comment by breandan** [comment]
Thanks for reporting. We don't use anything from the platform except [`FindModel`](https://github.com/acejump/AceJump/blob/627d86d6ea31b23334d55d331c221159d873d250/src/main/kotlin/org/acejump/search/AceFindModel.kt), but maybe there's some IDE state that's not being reset. Will investigate.

**Comment by breandan** [comment]
Thanks for the update. Maybe a platform issue, but feel free to reopen if this reappears. No idea what might have caused it.
