### ISSUE TITLE
Ace Jump stopped working with material theme in a angular project

### ISSUE THREAD

**Issue by kothagundlahari** [acejump/AceJump#257]
1. I am using the material them in Webstorm( Deep Ocean Theme).
2. When I press CTRL+; and I can see the focus in the file but after pressing the keys(no suggestion are being shown.)

Operating System:
1. Windows 10.
2. Webstorm (2018.2.5)

[log.txt](https://github.com/acejump/AceJump/files/2544200/log.txt)

**Comment by kothagundlahari** [comment]
the issue is resolved once I have rebooted my IDE(or my system).

**Comment by breandan** [comment]
Unable to reproduce but please feel free to reopen if you encounter this issue again.
