### ISSUE TITLE
Cursor colour changes to black after using AceJump

### ISSUE THREAD

**Issue by arsho78** [acejump/AceJump#263]
After the last update, the cursor pointer colour turns into black once activating AceJump. The pointer appears as in Insert mode if ideaVim is also activated. Entering and quiting Insert mode again will switch the pointer shape back to normal, but the colour is always black. It happens both in Linux and Windows. Restart Intellij Idea will temporarilly resolve this issue.  I am using Intellij Idea 2018.3.1 IU-183.4588.61, AceJump v3.5.2

**Comment by breandan** [comment]
Thank you for reporting this issue, will try to reproduce.

**Comment by RFV5s** [comment]
same here
<img width="329" alt="capture" src="https://user-images.githubusercontent.com/1437122/50067976-879c5000-01fe-11e9-80dc-e96693df5d4f.PNG">

**Comment by smallsmallwolf** [comment]
Same problem for me.
I tried the v3.5.1 and it no this bug.
You can fallback to [v3.5.1](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=50797) temporarily. 
@arsho78 @RFV5s

**Comment by breandan** [comment]
Should be fixed by updating to AceJump `3.5.3`. Please reopen if this is not the case.

**Comment by Kevin0010** [comment]
> 
> 
> Should be fixed by updating to AceJump `3.5.3`. Please reopen if this is not the case.

I'm using v3.5.4 and this problem still exists

**Comment by yuzhenzero** [comment]
> > Should be fixed by updating to AceJump `3.5.3`. Please reopen if this is not the case.
> 
> I'm using v3.5.4 and this problem still exists

I'm using v3.5.4 too, but I update IDEA to the latest version, the problem doesn't exist. You can try to update the IDEA. @Kevin0010

**Comment by breandan** [comment]
Unfortunately due to limited resources, we only really test AceJump against the latest IDE version before releasing, and as the IntelliJ Platform API changes from time to time, older versions may have bugs. We could be more careful with the `min/maxSdk` compatibility, but for now the best solution is to update if you encounter issues like this.

**Comment by Kevin0010** [comment]
> 
> 
> > > Should be fixed by updating to AceJump `3.5.3`. Please reopen if this is not the case.
> > 
> > 
> > I'm using v3.5.4 and this problem still exists
> 
> I'm using v3.5.4 too, but I update IDEA to the latest version, the problem doesn't exist. You can try to update the IDEA. @Kevin0010

我用的就是最新版的idea啊（2018.3.3），在win10和Linux下都试过了，还是一跳转就变黑啊，真的有毒…… @yuzhenzero 
I used the latest version of idea (2018.3.3), tried it under win10 and Linux, but the cursor still turned black after a jump, it is really a problem... @breandan
