### ISSUE TITLE
not work: select text between current position and the target position by pressing shift key when typing the last tag character 

### ISSUE THREAD

**Issue by arsho78** [acejump/AceJump#264]
Intellij Idea 2018.3.1 IU-183.4588.61
AceJump 3.5.2
Debian 9

**Comment by breandan** [comment]
I can reproduce this issue, thank you for reporting. Should be fixed in the next release.

**Comment by breandan** [comment]
Should be fixed by updating to AceJump `3.5.3`. Please feel free to reopen if this is not the case.
