### ISSUE TITLE
Cursor stays in 'wide' mode after cycling through AceJump modes

### ISSUE THREAD

**Issue by saroff** [acejump/AceJump#267]
1. Press `alt+;` twice.
2. Press `esc` to cancel search.

Result: cursor stays in wide mode.
![2018-12-24_16-34-43](https://user-images.githubusercontent.com/6500849/50400725-f8f97700-0799-11e9-9a93-dcdba660ee42.gif)

**Comment by breandan** [comment]
Good catch, thanks for reporting!
