### ISSUE TITLE
Incompatible with AndroidStudio 3.3?

### ISSUE THREAD

**Issue by ChrisZou** [acejump/AceJump#272]
Plugin search result inside AndroidStudio 3.3 does not acejump. I then downloaded the 3.5.4 zip file from https://plugins.jetbrains.com/plugin/7086-acejump, tried installing from disk, an error dialog showed: "Plugin 'AceJump' is incompatible with this installation".

**Comment by l1n3n01z** [comment]
Building from source on Windows, I also get the error in Android Studio 3.3. The plugin works fine from the plugin repository in IntelliJ Ultimate 2018.3.4

**Comment by TheKhaeng** [comment]
I also get the error in Android Studio 3.3

**Comment by breandan** [comment]
Can you try updating to [AS 3.4 RC1](https://developer.android.com/studio/preview) and reporting back? As specified [here](https://github.com/acejump/AceJump/blob/986e78978f4dd0ca3bd2bef0bdc060eafa8b2e87/src/main/resources/META-INF/plugin.xml#L20), the minimum required platform version for recent versions of AceJump is `182.5107.41`, perhaps AS 3.3 is based on an older version. If you would like to remain on AS 3.3, you can try installing an [older version of the plugin](https://plugins.jetbrains.com/plugin/7086-acejump).

**Comment by breandan** [comment]
The latest version of Android Studio (AS 3.4) should now be compatible with the latest version of AceJump `3.5.6`.
