### ISSUE TITLE
QWERTZ layout missing

### ISSUE THREAD

**Issue by rala72** [acejump/AceJump#273]
why is there no QWERTZ keyboard layout?

**Comment by breandan** [comment]
Not sure, but we can add it - feel free to submit a PR if you want, the code is [here](https://github.com/acejump/AceJump/blob/d4f9249727b35551f2a375059ab60b0133167c60/src/main/kotlin/org/acejump/label/Pattern.kt#L48) (the key distance prioritization is not working right now). Thanks for the suggestion!
