### ISSUE TITLE
Enter should exit out of AceJump when there is only one result on screen

### ISSUE THREAD

**Issue by oxysoft** [acejump/AceJump#274]
Currently you have to press Enter then Escape due to the new feature for jumping between several markers with enters.

**Comment by undsoft** [comment]
Second this. Doesn't make much sense to press any additional keys if result has already been found.

**Comment by undsoft** [comment]
Now that I'm thinking of this, should you even have to press Enter if there is one match?
Shouldn't the caret just jump to the match, if there is one one result? https://take.ms/jcRsq

**Comment by oxysoft** [comment]
If the caret jumps when there is only one match, the user can be confused as to where the caret went. It can also cause a race condition in the brain if it keeps flushing to the keyboard after the caret has jumped, meaning the user will enter text by mistake! I'm sure there are ways to do it such as waiting a delay after stopping typing and using visual effects to direct the eyes, but I'm not sure it's worth the effort.

**Comment by breandan** [comment]
Yes, we experimented with a similar feature a while back and received some negative feedback. While it is possible to consider such optimizations, in practice, it's better to have the user explicitly control the selection mechanism. Also, search mode has state transitions to other modes (e.g. via <kbd>Tab</kbd> or <kbd>Backspace</kbd>) that would be broken if we prematurely selected a solitary visible tag. So we will keep the <kbd>Enter</kbd>/<kbd>Shift</kbd>+<kbd>Enter</kbd> selection mechanism, even when there is a single tag.
