### ISSUE TITLE
Canary build link is broken

### ISSUE THREAD

**Issue by undsoft** [acejump/AceJump#277]
Link to canary builds in README.md leads to 404.

I was able to download canary version here: https://teamcity.jetbrains.com/viewType.html?buildTypeId=acejump_buildplugin&guest=1

**Comment by breandan** [comment]
Thank you for reporting. This due to jetbrains/gradle-intellij-plugin#377. The artifact you are looking for is located here: https://teamcity.jetbrains.com/viewLog.html?buildId=2057364&buildTypeId=acejump_buildplugin&tab=artifacts
