### ISSUE TITLE
Multi Caret Selection Mode

### ISSUE THREAD

**Issue by oxysoft** [acejump/AceJump#279]
Just an idea which I thought could work perfectly with AceJump's other existing features, and fits the name "AceJump" quite well I think. There is a shortcut I use religiously which is "Add Selection for Next Occurence". AceJump could have a mode which enters by pressing a different shortcut, and let's you navigate occurrences of the current word under the caret using: 

- Arrow keys to move between search results, starting with the word under the caret.
- SPACE/ENTER to toggle the selection on the active word.
- ESCAPE/ENTER to leave the mode.

When leaving the multi-caret editing (e.g. when pressing escape) the editor must return to a default caret. Usually this is the beginning location before leaving single-caret editing. For this mode, it could be done in many ways:

- HOME to leave the mode and set the active caret at the first location. (vertically)
- END same as above but last location. 
- ESCAPE/ENTER can be set by the user in the settings, defaults to start location.
- ACEJUMP to decide!?

I think this would be an insane editing tool because you could selectively discard occurrences (leave holes) which is a very common jerk in the workflow.

**Comment by breandan** [comment]
Bonjour @oxysoft, merci pour la suggestion. I believe @saroff had the idea first, is this the same as #221?

**Comment by oxysoft** [comment]
That issue does aim to achieve the same goal but I think the implementation is different from mine.

If I understand right, the main difference is suggesting we type the tag for each match. I think this won't scale well to many real life examples. The goal for the mode I described here is to be almost an extension to the `Add Selection for Next Occurrence` action of the IDE. The shortcut used to enter the mode should probably also reused as a selection toggle key within the mode too, that way a user could go as far as replacing the default shortcut for `Add Selection for Next Occurrence` with AceJump's, and the only difference would be that they'd have to press the toggle key again for the initial selection\* and ESCAPE/ENTER to leave the mode and begin the batch editing. If you enter the mode with text already highlighted in the editor, then it would search for it instead of the word under the caret, just like the default behaviour of the action. It would probably be best if the toggle action also advanced the cursor to the next match, but do offer an alternate toggle action too which doesn't advance and can be mapped to preference.

\* The reason it could be good to not immediately toggle the first match is that this feature could also double as a navigation feature: when leaving the mode with no selection, the caret should remain at the final location, that way we jump the caret between matches.

It is reinventing the wheel a bit in a way since this is basically the CTRL-F bar of the editor, but then again AceJump by default is also reinventing the mouse too. I think dedicated modes like these which integrate well into the keyboard to create a seamless workflow with low hand motion are the reason Vim and other similar editors flourish even today. The advantage of doing it this way is that we don't have to bind a bunch of crazy shortcuts to use convoluted actions from the search bar, you simply shift into a cool new contextual keyboard mode that has its own properties and easy shortcuts. Our hand is almost always hovering above the arrows, so the mode can be entered with a shortcut of the left-hand and then we can navigate straight away with UP and DOWN for example.

**Comment by oxysoft** [comment]
Hi, I have submitted to YouTrack a draft for a flexible and specialized code navigator which Jetbrains could add to their base platform https://youtrack.jetbrains.com/issue/RIDER-26434. This navigator at its core would allow navigation of a list of stops. It could also support a selection mode as described here, and I've taken the time to write it down on that page too.

The default behaviour of picking the word under the caret doesn't have to be an AceJump feature, but further features such as typing a random word in the file (using AceJump's tagging system) and converting to stops could be added. AceJump would simply have to start the navigator using a custom list of stops in order to extend it. AceJump could also have a feature to enter AceJump mode with the current stops in the active navigator, that way it results in a seamless experience between the navigator and AceJump.

This comment will certainly make more sense after reading the YouTrack article above but I have to warn you, it's also really really long. I believe only Resharper and Rider have Structural Navigation so far (C# only) so you may have to look it up to understand what it looks like.

**Comment by breandan** [comment]
Hi Nicolas, thank you for the detailed feature proposal. While I cannot promise to implement this, I can see the value of your proposal and [AceJump welcomes contributions](https://github.com/acejump/AceJump#contributing). Please let me know if you would be interested in working on this feature. If so, [MultiCaretCodeInsightAction](https://upsource.jetbrains.com/idea-ce/file/idea-ce-41ff102e050b2d16475edfd75df6094403b6ee10/platform/lang-impl/src/com/intellij/codeInsight/actions/MultiCaretCodeInsightAction.java) is a good place to get started.

**Comment by breandan** [comment]
I noticed that IdeaVim's multi-caret selection mode has recently improved. As [discussed here](https://github.com/acejump/AceJump/issues/350#issuecomment-753856650), I am a little hesitant to add features that overlap with IdeaVim functionality, although it may be possible to offer a smoother multi-caret integration. In any case, let's merge this discussion with #350. Thank you for the suggestion!
