### ISSUE TITLE
Accidentally dilabled Enter

### ISSUE THREAD

**Issue by olegkamuz** [acejump/AceJump#280]
Accidentally remove enter on keymap of Intellij Idea, after that on AceJump I can't hit enter and go to first search result appearance, as it was befory (shift+enter still works as usual). Trying to undo my removal, but can't find right keymap shortcut.

**Comment by breandan** [comment]
"Jump to first appearance" is bound the Editor Action named `Enter` (**Settings** | **Keymap** | **Editor Actions** | **Enter**).
