### ISSUE TITLE
Starting AceJump from a "rich renaming" text editing state should exit the state

### ISSUE THREAD

**Issue by oxysoft** [acejump/AceJump#283]
Steps to reproduce:

1- Use the IDE's rename refactor action on a local member of a method.
2- Activate AceJump in any mode and jump to a different location in the file.
3- Attempts to use ALT-ENTER to open the popup will fail (nothing happens) because the ALT-ENTER popup is disabled during renaming. This indicates strongly that the rename state is sticking around even after jumping, _even though_ the borders around the text edit have disappeared, for some reason.

This rename state of the editor that I'm talking about can also be entered in other different ways, such as using the "To property with serialized backing field" which I believe is an intention provided by the Unity plugin for Rider. After using the intention action, the rename state is entered on the backing field that was created, I'm guessing it must be a common IDE functionality.

Assuming this common renaming state exists and is reused for these different IDE features, entering AceJump mode should it cancel out.

Hope that was clear, thanks!

**Comment by breandan** [comment]
Thank you for reporting this issue, I am able to reproduce. Until it is fixed, try to avoid activating AceJump while in refactoring mode. In the meantime, if anyone else encounters this issue, it is possible to reset the renaming state by using the rename refactoring again and hitting escape to deactivate.

**Comment by breandan** [comment]
I tested this on `3.7.0` with `2021.1 EAP` and can no longer reproduce. I think it was most likely fixed by the IntelliJ Platform. Although activating AceJump does not immediately deactivate renaming, moving the cursor to a new location will.
