### ISSUE TITLE
Jumping in visual mode not working

### ISSUE THREAD

**Issue by xahon** [acejump/AceJump#288]
consider that line of code: `void SomeFunction();`
I want to copy the name of that method, so I place cursor on `S`, press `v` then I jump to `(` and visual mode gets changed to normal mode so I lose the selection

**Comment by AlexPl292** [comment]
That would be a nice feature! I'm also thinking about the ways we can better integrate AceJump and IdeaVim.

**Comment by breandan** [comment]
It would be great to have better integration with IdeaVim! Happy to help.

This issue related to #266.

In the meantime, AceJump currently provides its own selection mechanism. To select all text from the current caret position to a given tag location, just hold down `Shift` when typing the last tag character.

**Comment by MarioRicalde** [comment]
This is the behaviour that I was expecting when I installed it and I was quite surprised when it didnt work. The suggestion from @breandan really helps for the time being, but it'd be great to have this work with Visual as expected.

**Comment by AlexPl292** [comment]
@MarioRicalde Hi! The integration between IdeaVim and AceJump is implemented in `IdeaVim-EasyMotion` plugin: https://github.com/AlexPl292/IdeaVim-EasyMotion
