### ISSUE TITLE
The second key overlaps with the first key

### ISSUE THREAD

**Issue by Kevin0010** [acejump/AceJump#289]
I want to jump to the **JI** postion but after I put  **J** , **the **I** label is still alive** and the caret will jump to the **I** position after  I put **I**.

![before putting key](https://user-images.githubusercontent.com/39397413/58782618-ad34de80-8611-11e9-8085-6d322ae2f276.png)
_before putting key_

![after putting J ](https://user-images.githubusercontent.com/39397413/58782948-61366980-8612-11e9-9cdc-e2db63b5500b.png)
_after putting J_

![after puttion J and I,the caret go to the wrong position ](https://user-images.githubusercontent.com/39397413/58783002-7f9c6500-8612-11e9-9591-27dfef83ae45.png)
_after putting J and I,the caret go to the wrong position_

Sorry for my poor English.Hope that was clear.

Thanks!

**Comment by daxiaraoming** [comment]
and first label conflic with single label like "a" an "ae"

**Comment by breandan** [comment]
Thank you for reporting. IIRC there was some instability with the tagging mechanism in a release earlier this year. I believe this issue has since been fixed. Please feel free to re-open if this is not the case, and include a specific version number so we can diagnose. Thanks!
