### ISSUE TITLE
Add IDE actions for different AceJump shortcuts (improve remappability)

### ISSUE THREAD

**Issue by oxysoft** [acejump/AceJump#291]
Currently the only IDE actions offered by AceJump are the ones for starting it. Once AceJump is started, every key is hardcoded. Each key should be an IDE action in the AceJump category so that we can easily customize it to our liking. 

I personally would prefer to use TAB to scroll through hints (instead of ENTER) and ENTER to confirm (instead of ESCAPE), seems more intuitive to me and TAB is more quickly accessible after typing due to its position!

**Comment by breandan** [comment]
Relates to #172. This would indeed be nice to support, thank you for the suggestion.

**Comment by sauron918** [comment]
Yes, it would be a nice enhancement to have ability to customize another hotkeys.

For instance I would prefer to use arrow keys for navigation through search results instead of ENTER, SHIFT+ENTER.

**Comment by breandan** [comment]
Agreed. This is also related to #172, #215, #225 and part of a broader effort to improve AceJump customizability. Thank you for the feedback.

**Comment by breandan** [comment]
This was implemented in by @chylex in `3.7.0`. All of the AceJump shortcuts, including <kbd>Enter</kbd> and <kbd>Shift</kbd>+<kbd>Enter</kbd> should now be bound to IDE actions (<kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> still needs to be reimplemented as per #356).

**Comment by chylex** [comment]
Navigation via `Enter` and `Shift+Enter` is not rebindable, I just added shortcuts for all the default jump and line modes.

**Comment by breandan** [comment]
Hmm, I suppose we could also make these internal AceJump shortcuts configurable, although it would be simpler to have just one binding for each mode via the IDE actions. Since this ticket is specifically requesting IDE actions, let's open another ticket for that feature if it's something you feel is important.

**Comment by sauron918** [comment]
AceJump 3.8.3, is there so far an option to change the behavior of **arrow keys** ↑ ↓ in Cycle AjeJump Mode? 
I would like to use arrows keys instead of `Enter`/`Shift+Enter` cause it's more intuitive to me.
