### ISSUE TITLE
AceJump freezes IDE on 1,000+lines files

### ISSUE THREAD

**Issue by alexeygrantmyob** [acejump/AceJump#296]
In our codebase It's not uncommon to have files which are longer than 1,000 lines. AceJump is slowing down on a larger files (not ideal, but I can live with that), but when file reaches around 500 lines, keyboard shortcuts stop displaying, and on 1,000+ lines files the whole IDE will freeze and I only can kill in the Task Manager (on Windows).

**Comment by breandan** [comment]
Duplicate of #217, this is a critical issue and needs to be fixed ASAP. Thank you for your feedback.
