### ISSUE TITLE
Please update readme document,about shortcuts

### ISSUE THREAD

**Issue by shindo-l** [acejump/AceJump#302]
for example:
Target mode: Jump and select a full word in one rapid motion.<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + ;

Waiting for additional content(I don't know the shortcuts):
Line Mode: Jump to the first, last, or first non-whitespace character of any line on-screen.
Word Mode: Jump to the first character of any visible word on-screen in two keystrokes or less.
Declaration Mode: Jump to the declaration of a token (if it is available) rather than the token itself.

**Comment by breandan** [comment]
Line Mode is <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>;</kbd> by default, but the other modes do not have a default keybinding (to add one, open `Settings | Keymap | 🔍 "AceJump"`), however, they can be cycled through by pressing the default AceJump shortcut (<kbd>Ctrl</kbd>+<kbd>;</kbd>) repeatedly (once = normal mode, twice = target mode, thrice = target mode). This should be documented more clearly, feel free to submit a PR!

**Comment by tomsquest** [comment]
Additional changes needed (see #301):
This is wrong, it shoud be the third time, not second : `Press the AceJump shortcut a second time before completing a tag to activate Target Mode. Once Target Mode is activated, jumping to a tag will select an entire word`
