### ISSUE TITLE
Word motion paints incorrect labels during jump to two-letter tag

### ISSUE THREAD

**Issue by AlexPl292** [acejump/AceJump#310]
**Describe the bug**
During the word motion, tags are repainted after typing the first letter of the two-letter tag.

**To Reproduce**
1. Open a document with a lot of words and put the caret on the start of the document
2. Start AceJump in word mode
3. Type the first letter of any two-letter tag

Check the attached screencast. Note that I'm trying to select the `OP` tag and after I type `O` all the words that start with `o` are tagged. So, looks like AceJump performs a search at this moment.

I was able to detect that the issue appears first time on 6a2d15de34f62be4e0fb950234bd7a6a59148b00 commit. 
Seems like there is a bug somewhere in `Tagger` or `Finder` file.

![Screen Recording 2019-11-07 at 20 29 25](https://user-images.githubusercontent.com/4203721/68413053-7eadc780-019e-11ea-99cb-46d997b12d53.gif)

**Comment by breandan** [comment]
This has now been fixed in [`3.7`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/115735). Thank you for reporting!
