### ISSUE TITLE
Add AceJump jumps to IdeaVim jump list

### ISSUE THREAD

**Issue by Vozf** [acejump/AceJump#312]
it would be great if acejump jumps would be added to the vim jump list so jumping to previous location using ctrl+o and ctrl+i is possible 
ref https://vim.fandom.com/wiki/Jumping_to_previously_visited_locations

**Comment by breandan** [comment]
We add the jump locations to the IntelliJ Platform [history](https://github.com/acejump/AceJump/blob/bbc915f87d7383aee743a07b52dbb4aa44ff86dd/src/main/kotlin/org/acejump/search/Jumper.kt#L53-L59), however IdeaVim probably does not read from this. Is there an extension point for adding jump locations to the Vim jump list? @AlexPl292

**Comment by AlexPl292** [comment]
IdeaVim doesn't currently support jump lists: https://github.com/JetBrains/ideavim#summary-of-supported-vim-features

**Comment by Vozf** [comment]
Although ctrl+o and ctrl+i are working in ideavim

**Comment by blaxpy** [comment]
One way is to use IDE's actions for this:
```
nnoremap <c-o> :action Back<cr>
nnoremap <c-i> :action Forward<cr>
```

**Comment by AlexPl292** [comment]
The integration between IdeaVim and AceJump is presented in https://github.com/AlexPl292/IdeaVim-EasyMotion. To enable the feature in question, you can install this plugin (no need to enable it via `set easymotion`).

cc @breandan

**Comment by breandan** [comment]
Great! Although there still appears to be a discrepancy between the Back/Forward action behavior of the IntelliJ Platform (via `IdeDocumentHistoryImpl`) and the way `<C-o>`/`<C-i>` are handled in IdeaVim. Is it possible to merge them or is the default Vim behavior incompatible with the platform implementation?

**Comment by AlexPl292** [comment]
Yes, unfortunatelly. We are going to work with it along with reviewing this PR https://github.com/JetBrains/ideavim/pull/224

**Comment by breandan** [comment]
I believe this issue has been fixed and is now supported by IdeaVim.
