### ISSUE TITLE
Add keyboard shortcut for invoking Declaration Mode directly

### ISSUE THREAD

**Issue by clojj** [acejump/AceJump#317]
Are shortcuts configurable already somewhere ?

Not only would I like to have different keys, but also have target mode as the **first** mode

**Comment by breandan** [comment]
The AceJump shortcuts are configurable under **Settings | Keymap | 🔍 "AceJump"**, where you can add key bindings for specific modes. This is covered in the [configuration instructions](https://github.com/acejump/AceJump#configuring). Please let us know if this should be improved somehow.
<img width="1012" alt="Screen Shot 2019-11-27 at 11 14 45 PM" src="https://user-images.githubusercontent.com/175716/69784902-c86d4a80-116b-11ea-9553-8771737d6284.png">

**Comment by clojj** [comment]
yep, didn't know that... maybe the only thing missing is "DeclarationMode" (Navigate To)
?

**Comment by breandan** [comment]
Declaration Mode / Navigate To is already supported, although not visible in the above screenshot. There is no default keyboard shortcut but you can select one manually by selecting **Preferences | Keymap | 🔍 "Start in Declaration Mode"**. I will adjust the description so the Declaration Mode action keymap is visible by default in the search results.
