### ISSUE TITLE
Conflicts with JetBrains Rider default keyboard

### ISSUE THREAD

**Issue by shindo-l** [acejump/AceJump#320]
Sorry my english is not good

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Snipaste_2020-01-17_00-52-55](https://user-images.githubusercontent.com/44925133/72546803-60fb8d80-38c6-11ea-8905-f52723e6570a.png)

*Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 7 6.1
 - IDE and version 
JetBrains Rider 2019.3.1
Build #RD-193.5662.14, built on December 20, 2019
 - AceJump version 3.5.9

**Additional context**

**Comment by shindo-l** [comment]
also declaration mode not working
![Snipaste_2020-01-17_01-22-35](https://user-images.githubusercontent.com/44925133/72547836-63f77d80-38c8-11ea-9c33-3fa07e136c2f.png)

**Comment by breandan** [comment]
Thank you for reporting the shortcut collision. After changing the shortcut, did AceJump work as expected? Were you able to navigate to the symbol in the usual manner (e.g. by using <kbd>Ctrl</kbd>+Click)?

**Comment by shindo-l** [comment]
After changing the shortcut, did AceJump work as expected?
normal mode and target mode functioning normally, declaration mode not working

Were you able to navigate to the symbol in the usual manner (e.g. by using Ctrl+Click)?
Ctrl+Click or Ctrl+B can go to target symbol

**Comment by chylex** [comment]
Declaration mode in Rider was fixed a while back. I don't know if there is a way to set different defaults for shortcuts based on the IDE (maybe an optional dependency on Rider in plugins.xml might work, but not sure). Do you think it's worth coming up with a separate set of defaults, or is it ok to just let Rider users rebind them manually?

**Comment by shindo-l** [comment]
hi chylex,thank you comment.
I opened a new issue to collect everyone's opinions,so I closed this issue

ask for advice about Rider AceJump shortcut · Issue #386 · acejump/AceJump
https://github.com/acejump/AceJump/issues/386
