### ISSUE TITLE
Make AceJump dynamic loaded

### ISSUE THREAD

**Issue by AlexPl292** [acejump/AceJump#322]
It would be great if someday it would be possible to load and unload AceJump without restart.

It doesn't seem as a big problem since only that has to be done is to get rid of application component.

https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/dynamic_plugins.html

**Comment by breandan** [comment]
Now supported as of [AceJump 3.6+](https://plugins.jetbrains.com/plugin/7086-acejump/update/84201). Tested dynamic reloading on `IU/WS/PC-2020.1`. Amazing!
