### ISSUE TITLE
In IDEA 2020.1, enable IdeaVim-EasyMotion and AceJump, It will throw exception and stop working.

### ISSUE THREAD

**Issue by HeWenJin** [acejump/AceJump#324]
**Describe the bug**
On my computer, use IdeaVim-EasyMotion 1.2 , AceJump 3.6.0 and IdeaVim 0.56, Start up IDEA will report this exception, and it make IdeaVim plugin stop working too. Then I discovery, disable IdeaVim-EasyMotion and restart IDEA, this error will be disappear.

**Expected behavior**
Wish to fix this bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/30885216/79686392-9e2f3d00-8272-11ea-8f2c-27d0c5995e54.png)

**Desktop (please complete the following information):**
 - OS: win10 1909
 - IDE and version: IntelliJ IDEA 2020.1
 - AceJump version: 3.6.0
 - IdeaVim-EasyMotion: 1.2
 - IdeaVim: 0.56

**Comment by 3dot141** [comment]
yes,   i am in the same situations

**Comment by antsbean** [comment]
yes, i am in the same situations

**Comment by rootial** [comment]
it can still work if you downgrade the AceJump to 3.5.9, hope this can help u temporarily. @HeWenJin 😄

**Comment by HeWenJin** [comment]
> it can still work if you downgrade the AceJump to 3.5.9, hope this can help u temporarily. @HeWenJin 😄

yeah, this could work, thx

**Comment by AlexPl292** [comment]
Here is a PR with a possible fix: https://github.com/acejump/AceJump/pull/326

**Comment by breandan** [comment]
This should be fixed in [AceJump 3.6.1](https://plugins.jetbrains.com/plugin/7086-acejump/update/84201). Please feel free to update. Thanks to @AlexPl292 for the PR!
