### ISSUE TITLE
CodeVision interfering with backward navigation

### ISSUE THREAD

**Issue by AKJ1** [acejump/AceJump#329]
**Describe the bug**
What happens is when CodeVision is enabled, additional infomration is displayed, messing with the size of the file. This interacts poorly with AceJump's internal tracking of what portion of the file is open, and doesn't generate enough navigation symbols to cover the entire visible portion of the file. This only applies to backward symbols. There's a hard cutoff.
The more occurances of contextual CodeVision information there are before the cursor position, the less navigation symbols will be generated. 

**To Reproduce**
1. Be on any IDE that supports CodeVision. Rider's a good bet.
2. Edit a file large long enough for these errors to accumulate.

**Expected behavior**
Navigation symbols should be generated for every relevant match preceeding the cursor  for the entire visible part of the file.

**Screenshots**
Screenshot: 
![image](https://user-images.githubusercontent.com/6927882/82129131-3a445980-97c9-11ea-90a2-6b5c7fc1bab0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - IDE Rider 2020.1
 - AceJump 3.6.1

**Additional context**
Many CodeVision Annotations are generated for Unity Development.  This issue wouldn't be as severe on smaller files.  I would speculate that the same would apply to Unreal as well. CodeVision instances are those bits of extra data that appear above method declarations.

**Comment by Jaap-van-Hengstum** [comment]
Since the method of calculating the screen boundaries seems to be adapted from the IdeaVim code, [https://github.com/JetBrains/ideavim/pull/173](https://github.com/JetBrains/ideavim/pull/173) was the pull request that fixed the IdeaVim code to take into account the Code Vision layouts.

**Comment by breandan** [comment]
This should be fixed in [`3.7.0`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/115735). Feel free to give it a try and leave your feedback!
