### ISSUE TITLE
Line mode clutters for lines with less than 3 visible characters

### ISSUE THREAD

**Issue by Mishkun** [acejump/AceJump#340]
**Describe the bug**
When entering line mode, lines with no characters get only zero position highlighted for jump. However, lines with 1-2 characters highlight 0, first visible and last position. This causes visual artifacts.

**To Reproduce**
Activate line mode with the line with 1 char only

**Expected behavior**
I think we can enable only 0 and end position for such cases.

**Screenshots**

![image](https://user-images.githubusercontent.com/12541804/99670716-043aa780-2a82-11eb-97a8-915fb5b6cadd.png)
![image](https://user-images.githubusercontent.com/12541804/99670713-01d84d80-2a82-11eb-99d5-8c4d5a2a1770.png)

**Desktop (please complete the following information):**
 - Acejump 3.6.3

**Comment by breandan** [comment]
Thank you for reporting. This issue is a duplicate, please follow  #228 for updates.
