### ISSUE TITLE
I implemented a few features and improvements

### ISSUE THREAD

**Issue by chylex** [acejump/AceJump#342]
I started a branch for experimenting with various features, let me know if you'd like me to make a PR for any of these.

1. ~~Customizable order of jump modes when repeatedly pressing the Activate key~~ (#344)
2. ~~Customizable color for definition mode~~ (#343)
3. ~~Jump mode that jumps to the end of the word~~ (#347)
4. ~~Pressing keys dedicated to a specific mode toggles the mode on/off (it looks like this was intended in the first place, but currently the toggle keys don't reset the mode properly)~~ (#344)
5. ~~Removed rounded corners on tags (it would probably be better to make it configurable instead, but with my particular font settings the edges were rounded too much and made it more difficult to read the tags)~~ (#346)
6. ~~Custom config serialization for colors so that you don't have to define separate properties for `Color.rgb` (it's compatible with old configs)~~ (#343)

![obrazek](https://user-images.githubusercontent.com/3685160/99830288-c90da680-2b5d-11eb-919f-81cb35d43ccd.png)

**Comment by breandan** [comment]
All these seem like good features to me! I would prioritize the ones you would find most useful, some of these might overlap [other feature requests](https://github.com/acejump/AceJump/labels/feature), and (4) seems more like a bugfix. Feel free to submit the proposed configuration changes as a single PR for if it's more convenient.

**Comment by chylex** [comment]
Configuration is in #343. I'll PR jump mode cycling next (+ toggle fix) based off of the configuration branch.

**Comment by chylex** [comment]
Updated the original comment and striked through all features that I made PRs for.

**Comment by chylex** [comment]
With #345 that lets you limit search to what's on screen, I have some an idea that could make keyboard extremely powerful:

* A keybind that acts on all currently highlighted words, depending on the current mode:
  * **Jump mode** places a caret at the beginning of every word
  * **Jump to end mode** (if accepted) places a caret at the end of every word
  * **Target mode** selects every word in multicaret mode
  * **Define mode** ???

I also thought about the regex modes, and assuming it wouldn't get too complicated for users to understand, it could work like this:

* A keybind that cycles between different regex modes, with configurable order like in #344 
* A text field where you can specify a custom regex, and have the option to cycle to it using the keybind ^ or a custom keybind to toggle it

What do you think?

**Comment by breandan** [comment]
> A keybind that acts on all currently highlighted words, depending on the current mode: 

Interesting. This multicaret functionality seems related to a longstanding feature request, #279.

I don't have the time to review it this week, but @oxysoft might be able to give you some feedback.

Thank you for the nice feature PRs! I was able to confirm they work as described.

**Comment by chylex** [comment]
I think it'd be worth figuring out a way to handle existing multicarets when entering AceJump mode, and also having a mode where you pick which places you want to add a caret to, but my idea is just to have a really quick way to jump to/select all matching places at once. It seems to work quite well, but still not sure what to do about Define mode.

**Comment by chylex** [comment]
I noticed that the tag assignment only counts the first word when narrowing tags, so sometimes you run into issues where you type past the first word (for ex. `obj.func`) and have a chance of hitting a marker while still typing. Similar issue happens when starting a regex search and starting to type (for ex. in line start mode, you can type `import` to narrow down to import lines). I'll think about how that could be solved, I'm not against recomputing all tags as soon as you go past a single word because I don't think it'll happen too often, but it's a nice-to-have sometimes.

**Comment by breandan** [comment]
We use the right boundary [plus a few characters](https://github.com/acejump/AceJump/blob/c5008ab26eb55ed4fdb96e7611f5b3bfca16fd13/src/main/kotlin/org/acejump/search/AceUtil.kt#L74) to filter out tags starting with characters from the beginning of the next word, but in rare cases matching characters from the next word can result in a tag collision. To reduce the likelihood of a collision, we could set a minimum lookahead, or filter from the next k words, although this would increase average latency, so it's a tradeoff. Once we assign a tag, the last character of a two-character tag may sometimes be discarded if it is no longer needed to ensure uniqueness, but we never change the first tag character to avoid surprising the user.

**Comment by breandan** [comment]
It looks like these suggestions have all been implemented, thank you! Feel free to open another issue for multi-caret functionality.

**Comment by oxysoft** [comment]
I have started using Vim and IdeaVim a year ago so I'm not sure how useful these features will be anymore. My editing patterns have all flipped upside down and I don't find as much uses for AceJump or multi-caret for that matter.

The changes here look very good, I would definitely integrate some batch actions on tags into my workflow. @chylex I suggest implementing them as IDE actions if not done already. For example, these actions:

```
AceTagToCarets
AceTagToCaretswordStart
AceTagToCaretswordEnd
```

If you wanna please Vim users, there is the concept of a special **W**ord class which is delimited only by space. Whenever we use uppercase W or E, we are speaking in terms of space-delimited words, as opposed to lowercase w and e which consider everything outside of letters and numbers to be word delimiters. (hence why I left the w for word all in lowercase in my mockup IDE action names)

**Comment by chylex** [comment]
@oxysoft I implemented a multi-caret mode with a completely different jump system in https://github.com/acejump/AceJump/issues/350, but it doesn't work with IdeaVim-EasyMotion at the moment.
