### ISSUE TITLE
Reimplement IdeaVim integration

### ISSUE THREAD

**Issue by breandan** [acejump/AceJump#354]
Need to reimplement #307 post-refactoring.

**Comment by breandan** [comment]
All right, after merging #353 and reimplementing listeners, I think we have arrived at a solution that restores the functionality which [IdeaVim-EasyMotion](https://github.com/AlexPl292/IdeaVim-EasyMotion) expects. Although b33ae48 uses [`SearchProcessor`](https://github.com/acejump/AceJump/commit/b33ae482b07a4772a7a69dbde182856a836b2630#diff-307b2fda5064b8681c1a96b08f0dfb6a7face3075240eaf912e73af4e6601dccR147) in a way I'm not sure @chylex intended, it seems to be working.

The way these changes affect @AlexPl292 should be minimal. The major difference is that AceJump is now [`Session`](https://github.com/acejump/AceJump/blob/master/src/main/kotlin/org/acejump/session/Session.kt)-based. 

Callers who pass an instance of `Editor` into `SessionManager.start(editor)` will receive an `Session` instance in return. Looking at how IdeaVim-EasyMotion is [using us](https://github.com/AlexPl292/IdeaVim-EasyMotion/blob/3d7f0ce81bde9a2cb20a59b58bd290f1c9f30772/src/main/kotlin/org/jetbrains/plugins/extension/easymotion/AceJumpToJumpList.kt#L36), I'm pretty this should not be an issue, since an editor is usually in scope. Sessions are disposed after use.

To use AceJump externally, please use the following example:

```kotlin
import org.acejump.session.SessionManager
import org.acejump.session.AceJumpListener
import org.acejump.boundaries.*

val aceJumpSession = SessionManager.start(editorInstance)

aceJumpSession.addAceJumpListener(object: AceJumpListener {
  override fun finished() {
    // ...
  }
})

// Sessions provide these endpoints for external consumers:

/*1.*/ aceJumpSession.markResults(sortedSetOf(/*...*/)) // Pass a set of offsets
/*2.*/ aceJumpSession.startRegexSearch("[aeiou]+", WHOLE_FILE) // Search for regex
/*3.*/ aceJumpSession.startRegexSearch(Pattern(/*...*/), VISIBLE_ON_SCREEN) // Search for Pattern
```

Unless there are any objections, I am planning to release these changes with `3.7.0`.

@AlexPl292 @chylex Please let me know if you have any questions or concerns.

**Comment by chylex** [comment]
I think the use of SearchProcessor is fine, can't think of any issues.

**Comment by AlexPl292** [comment]
Yay, glad to see such a big update of AceJump!
The sad note is that IdeaVim-EasyMotion integration was a bit ruined by these changes (no surprise, as I see almost everything was updated), so at the moment I've preformed a hot release just to make it compatible with the 3.7 version. A bit later, I'll dive into it to restore all the functionality.

@chylex great work! 🎉

**Comment by breandan** [comment]
I apologize for the disruption, you can blame me for ruining IdeaVim-EasyMotion and thank @chylex for fixing almost all our outstanding bugs. In the future, I will try to coordinate and communicate breaking changes in a more timely manner.
