### ISSUE TITLE
Issues with files without new line at the end

### ISSUE THREAD

**Issue by AlexPl292** [acejump/AceJump#360]
Some operations with "end" have issues when the files doesn't contain a new line symbol at the end

E.g.:
1) Use "AceJump in all lines end mode".
2) Last line is not highlighted. 

There is a method `getHighlightLength` that returns always `1` for regex search. I don't know why it's 1, but because of
that the last offset is not considered as correct.
 
![2021-04-09 10 23 51](https://user-images.githubusercontent.com/4203721/114144480-0cef2580-991e-11eb-8bba-51ac73bae5f3.gif)

**Desktop (please complete the following information):**
 - OS: macOs
 - IDE and version 2021.1
 - AceJump version 3.7

**Comment by chylex** [comment]
Please try the version in `master` and see if there are no issues with easymotion, I had to make some subtle changes that might potentially be breaking for API users.
