### ISSUE TITLE
Highlight offset difference on high-DPI screens

### ISSUE THREAD

**Issue by AlexPl292** [acejump/AceJump#362]
Labels and highlighted text have height differences and this looks inaccurate. 

![image](https://user-images.githubusercontent.com/4203721/114145437-0dd48700-991f-11eb-941f-01e9e0212e02.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - IDE and version 2021.1
 - AceJump version 3.7

**Comment by chylex** [comment]
I actually have no idea what exactly causes it, I noticed it on Mac and came up with a workaround which seems to work - at least on my particular DPI settings - but I don't know if it's actually safe to PR it like this. https://github.com/chylex/IntelliJ-AceJump/commit/2ca21b84239013fc001cd80a11f325677b8c8c8f

**Comment by chylex** [comment]
Since this is still open, I'll see if my "fix" works on other DPI settings and PR it.
