### ISSUE TITLE
Place cursor at the end of typed text in normal mode

### ISSUE THREAD

**Issue by MichaelMedvedskiy** [acejump/AceJump#364]
**Is your feature request related to a problem? Please describe.**
I feel quite frustrated when I enter some text, then press the key combination, and the cursor positions itself at the beginning of the typed text.
Example (what I type and move to is in bald)
public static void **main(** String[] args).....

I expect the cursor to end up before 'S', it ends up before 'm'.

The most unnoying example of this is when I have a semicolon at the end of a line, I type a semicolon (because I want to get to the end of the line, and when my screen is not greyed out it's more convenient to navigate to the end of a certain line, as it is in general more convenient for me to do all the moving with one combination - ctrl+;), and the cursor ends up before the place where I need it, and I have to manually replace it.

**Describe the solution you'd like**
I would like there to be an option which when switched on, would place the cursor at the end of typed text in normal mode.

Thank you for your time, Mike.

**Comment by breandan** [comment]
Hi @MichaelMedvedskiy, thank you for your feedback. This feature was recently implemented and is available in AceJump `3.7.0`, please see [this comment](https://github.com/acejump/AceJump/issues/225#issuecomment-817371714) for details how to enable it.

**Comment by MichaelMedvedskiy** [comment]
thank you kindly!
