### ISSUE TITLE
Support for split screen

### ISSUE THREAD

**Issue by helmus** [acejump/AceJump#370]
This would be extraordinary useful as it in fact eliminates the need to switch between tabs. Super super useful.
Willing to put down a bounty of up to 200$ if anyone feels like committing to it.

**Comment by helmus** [comment]
@chylex any chance you would be interested in picking this up ?

**Comment by chylex** [comment]
Sounds interesting, I would find use for this as well. I'll give it a few hours and see how easy it would be to add multi-editor sessions, since at the moment the assumption is 1 editor = 1 session.

**Comment by breandan** [comment]
I started working on this feature some time ago (#144), but decided to make it into a desktop application and forked a [new project](https://github.com/acejump/tracejump). It's not what you want exactly, but should be possible use to select any text visible on the screen. I agree that mutieditor/multiwindow support would be nice support within AceJump. If you were able to hook into the IDE text rendering pipeline, you could tag menus and other text in the IDE, then click on things using the [AWT Robot](https://docs.oracle.com/javase/7/docs/api/java/awt/Robot.html), but that's probably more trouble than it's worth.

**Comment by chylex** [comment]
A while back I opened [IDEA-264270](https://youtrack.jetbrains.com/issue/IDEA-264270) which is about clicking IDE buttons using AceJump-style shortcuts, if a plugin could do that (+ tagging menus etc.) it'd be brilliant.

**Comment by breandan** [comment]
As you mentioned, platform support for these kinds of features is currently poor, but better interoperability with [screen readers](https://en.wikipedia.org/wiki/Screen_reader) is an important [accessibility feature](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009718839-Using-IntelliJ-with-a-screen-reader) for blind and visually impaired users. I believe it is possible, but would require intercepting the IDE rendering pipeline somehow to extract the visible clickable UI elements. If you can get this to work, I will double @helmus' bounty.

**Comment by chylex** [comment]
Progress - tagging is *very* broken but rendering and jumping across splitters works:

![obrazek](https://user-images.githubusercontent.com/3685160/117376950-76893200-aed2-11eb-98fb-b351d0d3374b.png)

**Comment by chylex** [comment]
Looking good

https://user-images.githubusercontent.com/3685160/117386477-48fab380-aee7-11eb-8be4-f6dad576e6b0.mp4

**Comment by helmus** [comment]
👏 👏 👏 

<a href="https://www.bountysource.com/issues/98311977-support-for-split-screen" ><img src="https://api.bountysource.com/badge/issue?issue_id=98311977"></a>

**Comment by breandan** [comment]
Nice! What happens when you search for text outside the screen boundaries? Do you plan to disable auto-scrolling in split-screen sessions or do you think it makes sense to scroll multiple editors to the nearest available match? It might be a good idea to disable uppercase/shift selection when switching between editors, but work within editors. Cycling with Enter/Shift enter also becomes tricky, not sure how you're planning to handle that.

**Comment by helmus** [comment]
Absolutly no editor scrolling please. Visual area **ONLY**, this is very important for usability and performance.

**Comment by breandan** [comment]
Ideally, AceJump's scrolling behavior should respect the `Search whole file` settings option, but perhaps we can make an exception when multiple editors are open if that behavior becomes too complicated to implement or does not make sense from a usability standpoint.

**Comment by chylex** [comment]
> Nice! What happens when you search for text outside the screen boundaries?
> Cycling with Enter/Shift enter also becomes tricky

At the moment I implemented it in my experimental fork, which has both of these options completely removed, I'm starting to port it to upstream master so I'll see how it works out.

> It might be a good idea to disable uppercase/shift selection when switching between editors

Definitely, it *technically* works because each editor remembers its caret position, but it's confusing.

**Comment by breandan** [comment]
I have confirmed that split-screen navigation works as described and is available immediately in [`3.8.0`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/119412). Thanks to @chylex for this great contribution!

**Comment by chylex** [comment]
I set an "in progress" status on the bounty, it says I'll be able to claim it once the issue is closed. Can't remember if you have to do that or if it takes a while to update automatically.

**Comment by chylex** [comment]
Claimed, thanks.
