### ISSUE TITLE
"Cannot find declaration to go to" in Rider

### ISSUE THREAD

**Issue by Pilvinen** [acejump/AceJump#379]
**Describe the bug**
"Cannot find declaration to go to" every time when using Declaration Mode. Using the IDEs "Go To" menu does not result in the same error.

**To Reproduce**
1. Tap to declaration mode.
2. Type in the name and select.
3. See error.

**Expected behavior**
1. Tap to declaration mode.
2. Type in the name and select.
3. AceJump jumps to the declaration as if I were using the "Go To" menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/4374351/124352784-395bca80-dc0b-11eb-85fd-3711ea437490.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - IDE and version: JetBrains Rider 2021.1.3
 - AceJump version: 3.8.3.

**Additional context**
Awesome addon!

**Comment by Pilvinen** [comment]
I noticed that this seems to be an issue with "Declaration" but not with "Declaration and Usages":

![image](https://user-images.githubusercontent.com/4374351/124353085-f7cc1f00-dc0c-11eb-8f06-3b2082952678.png)

The declaration alone seems to have been removed from Riders "Go To" menu and it now has only "Declaration and Usages" available. To use the "Declaration" only option I have to look it up through Riders "search everywhere" (in other words, the "Declaration" only option cannot be accessed from the normal menus by default). And the "Declaration" only never seems to work - with or without AceJump.

Maybe it's been phased out in favor of "Declaration and Usages"? But that's just my guess.

**Comment by Pilvinen** [comment]
I asked about it further from JetBrains devs:
![image](https://user-images.githubusercontent.com/4374351/124385972-af7e3100-dce0-11eb-90b0-a26eb7d77551.png)

And they told me that:
![image](https://user-images.githubusercontent.com/4374351/124385914-82ca1980-dce0-11eb-91f6-cfd2a294c1cc.png)

**Comment by breandan** [comment]
Thank you for looking into this. Jumping in AceJump's **Declaration mode** is intended to produce the same result as pressing <kbd>Ctrl</kbd>/<kbd>⌘</kbd>+[Click] on the token in the editor -- we currently use the [`GotoDeclarationAction`](https://github.com/JetBrains/intellij-community/blob/bd0196f4b3c23ef0477bc50a3d4dcd6f67ae06ad/platform/lang-impl/src/com/intellij/codeInsight/navigation/actions/GotoDeclarationAction.java) to simulate this, but if I understand what @Pilvinen is saying correctly,`GotoDeclarationAction` is not a cross-platform solution across all IntelliJ Platform products and in particular, does not work in Rider. @igor-akhmetov Can you please clarify what is the correct IntelliJ Platform action we should invoke to simulate a mouse-click navigation event? Thank you.

**Comment by igor-akhmetov** [comment]
@breandan, I believe you should be using `ActionManager` to instantiate the required actions instead of creating them directly. I.e. in your case you should use `ActionManager.getInstance().getAction(id)` where `id` is `"GotoDeclaration"` or `"GotoTypeDeclaration"`. This approach will also work in Rider, which has its own "goto declaration" actions which communicate with the Rider backend process.

**Comment by chylex** [comment]
In case you don't want to use hardcoded strings, there are constants in `com.intellij.openapi.actionSystem.IdeActions`:
```java
IdeActions.ACTION_GOTO_DECLARATION
IdeActions.ACTION_GOTO_TYPE_DECLARATION
```
