### ISSUE TITLE
Don't display the tag string when I enabled Acejump mode

### ISSUE THREAD

**Issue by tabuyos** [acejump/AceJump#381]
**Describe the bug**

The tag string is not display when I press `Ctrl-;` and type some keys. I found a similar one #376 , but, I disabled the checkbox that `show hint with search text`

**Screenshots**

![image](https://user-images.githubusercontent.com/45193148/125887453-a08628fd-f9ef-4c96-967c-b09fe7979411.png)

![image](https://user-images.githubusercontent.com/45193148/125886997-5cc90534-629d-4d27-9c78-79a5615fc921.png)

![image](https://user-images.githubusercontent.com/45193148/125886823-f102537c-eb09-417a-aba9-4f24511f4932.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19043
 - IDE: IntelliJ IDEA 2021.1.3 (Ultimate Edition)
 - AceJump: 3.8.3

**Comment by breandan** [comment]
What are the contents of the field `Allowed characters in tags:`? Can you provide any further details how to reproduce?

**Comment by tabuyos** [comment]
> What are the contents of the field `Allowed characters in tags:`? Can you provide any further details how to reproduce?

The content of `Allowed characters in tags:` is `0123456789abcdefghijklmnopqrstuvwxyz`, which is a default value


I don't remember when this problem started. Up to now, I think it should work normally a week ago. Is it because I installed some plug-ins that caused incompatibility?

**Comment by tabuyos** [comment]
Uh-oh! When I tried to close my new plug-ins, I found a bad thing when I enabled `active-power-mode` plug-in, the tag string would not be displayed, if disabled the new plug-in it's work! That's crazy.

Thank you bro.

**Comment by tabuyos** [comment]
Because I don’t use the mouse much when coding, I think `AceJump` helps me more, so I have to turn off the `active-power-mode` plugin, which is a frustrating thing.
