### ISSUE TITLE
One-character tags are matched instead of two-characters tags

### ISSUE THREAD

**Issue by Lepruz** [acejump/AceJump#391]
**Describe the bug**
Hi, I've recently found out that sometimes my cursor jumps to a wrong place. When there are so many lines that I have both one-character and two-character tags it always jumps to the former. Let's assume that there is  **T** tag and **FT** tag on the screen. You want to jump to the **FT**, so you type `F` and then `T` - you are landing on **T** tag line instead of **FT**.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open file with so many lines that there are one-character tags all together with two-character.
2. Pick two-character tag (e.g. **FT**) that ends with letter that has its corresponding one-character tag (in this case it is **T**).
3.  click `ctrl+;` to launch `AceJump`.
4. Type `F` on you keyboard and then type `T`.
5. You land on the line tagged by one-character **T**.

**Expected behavior**
You land on the line tagged by two-character tag (in this face **FT**)

**Screenshots**
Please note that I had already typed `F` in order to move to the line 27.
<img width="645" alt="Screenshot 2021-12-19 at 13 59 42" src="https://user-images.githubusercontent.com/42671368/146676003-09243729-5084-48bd-b950-a6ef2f16fae8.png">
And eventually cursor moved to the line 19 tagged by plain **T**.
<img width="519" alt="Screenshot 2021-12-19 at 13 59 56" src="https://user-images.githubusercontent.com/42671368/146676011-dddbaf94-574a-4d12-a327-1ba4b6838e2c.png">

**Desktop (please complete the following information):**
 - OS: iOS, Windows 10
 - IDE and version: Rider 2021.3, IntelliJ 2020.3, Webstorm 2020.3
 - AceJump version: 3.6.3

**Comment by breandan** [comment]
Based on your description, it would appear that you are using an older version of AceJump. Could you please update to platform version `2021.3` with AceJump `3.8.5` and report back if this issue is still present? Many tagging bugs have been fixed since `3.6.3`, I believe this specific issue was fixed in #289 and #327.

**Comment by Lepruz** [comment]
Sorry for unnecessary noise, after upgrading IntelliJ to 2021.3 bug disappeared - it is fixed :)
