### ISSUE TITLE
AceJump "Declaration Mode" puts file in readonly mode when target is in different file

### ISSUE THREAD

**Issue by Mishkun** [acejump/AceJump#393]
**Describe the bug**
When jumping using declaration mode from file A to file B, AceJump does not make file A writable after jump. Any attempt to edit this file when returning back fails with popup "file is readonly". I need then to reset file to be writable again by marking it read-only and then writable.

**To Reproduce**
1. Use AceJump in Declaration Mode to jump to declaration located *in another file*
2. Go back using *Navigate -> Back* action
4. Try to edit file

**Expected behavior**
File is editable after returning back

**Desktop (please complete the following information):**
 - MacOS Big Sur 11.4
 - Android Studio Arctic Fox 2020.3.1 Patch 3 (based on IC 2020.3.1)
 - AceJump version 3.8.4

**Additional context**
I also have IdeaVim installed

**Comment by breandan** [comment]
Sorry for the late reply, but I was unable to reproduce this issue on the latest version of AceJump and IntelliJ IDEA. Please feel free to reopen if you encounter it again. Thanks.
