### ISSUE TITLE
Suggestion: fuzzy search

### ISSUE THREAD

**Issue by unlocomqx** [acejump/AceJump#402]
**Is your feature request related to a problem? Please describe.**
I'd like to jump to a symbol by using fuzzy search

**Describe the solution you'd like**
For example to jump to the variable `product_config`, I can type `pc`

**Describe alternatives you've considered**

**Additional context**
It would be also great to be able to jump to any symbol, even props like `option.id_option_group` (for example using `iog`)

**Comment by breandan** [comment]
Hey, thank you for the suggestion. I've thought about how to implement what you're describing and I think it might be possible but will require rearchitecting our tag assignment algorithm. There are several conventions including `CamelCase`, `snake_case` and `point.case` but I think they can be unified into a single algorithm. We would need to test it to ensure tag collisions are very rare. PR's welcome!

**Comment by unlocomqx** [comment]
Thank you for looking into this, I appreciate it!
