### ISSUE TITLE
Rename the `AceWordStartAction` ID in plugin.xml

### ISSUE THREAD

**Issue by colossatr0n** [acejump/AceJump#403]
**Is your feature request related to a problem? Please describe.**
The `AceWordStartAction` in `plugin.xml` could be renamed to better represent what it does. It also might be the case that I'm misunderstanding the naming convention.

**Describe the solution you'd like**
In `plugin.xml` there are the following two actions:

```xml
    <action id="AceWordStartAction"
            class="org.acejump.action.AceAction$ToggleJumpMode"
            text="Start AceJump in Jump Mode"/>
    <action id="AceWordEndAction"
            class="org.acejump.action.AceAction$ToggleJumpEndMode"
            text="Start AceJump in Jump End Mode"/>
```
The `AceWordStartAction` action gives the impression that the cursor will start at the beginning of the word, but when inspecting the code for `ToggleJumpMode`, the cursor jumps to the first character in the query search.

The `AceWordEndAction` action seems to be appropriately named since it will jump to the end of word that matches the search query.

I'm wondering if `AceWordStartAction` would be better named as something like `AceWordAction` or `AceWordCaretAction`. One thing to note is that if the name were changed, it might break the API for some people.

**Describe alternatives you've considered**
Maybe I misunderstand the meaning of "WordStartAction" and "WordEndAction."

**Additional context**
I'm using `JumpMode.kt` to understand the naming conventions of the IDs.

**Comment by breandan** [comment]
Hi @colossatr0n, thanks for reading carefully! I think you're probably right, we did not give much thought to naming conventions. There is currently no action that jumps to the start of a word like you're thinking (where a word is defined as text surrounded by whitespace). The closest thing is `AceTargetAction` which selects a chunk of non-whitespace text. One way to parse this is `AceWord` is whatever query the user types: `AceWordStart` drops the caret at the start of that query and `AceWordEnd` drops the caret at the end of the query. AceJump is generally very liberal to refactoring PRs which do not break existing functionality, so please feel free to dig through the code and rename/refactor wherever it makes sense.

**Comment by chylex** [comment]
The IDs are (at minimum) used for saving user keymaps, so changing them would break key bindings for existing users.

**Comment by breandan** [comment]
Good point, I've worried about changing IDs stored in static XML files before. It seems to me that there should be a way to migrate names without requiring users to reconfigure their settings after updating, but requires some extra logic. At least there is some flexibility with the presentation so even if the ID stays the same, we could make the text more descriptive.
