### ISSUE TITLE
Release request for PR #401.

### ISSUE THREAD

**Issue by colossatr0n** [acejump/AceJump#408]
This is a release request for https://github.com/acejump/AceJump/pull/401. 

Wondering if the changes in https://github.com/acejump/AceJump/pull/401 can be released as a new minor/micro plugin version.

Thanks!

**Comment by breandan** [comment]
#401 is included in [4.8.8](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/189931) and now available. Thank you once again for your contribution!
