### ISSUE TITLE
Is there a way to reset the color scheme to the default color scheme?

### ISSUE THREAD

**Issue by robbporto** [acejump/AceJump#411]
**Is your feature request related to a problem? Please describe.**
I changed my color scheme and now I want the original color scheme back. I can't see an easy way to do this.

**Describe the solution you'd like**
It would be good to have a "reset to default color scheme" button.

**Describe alternatives you've considered**
I've tried uninstalling and installing the plugin but the old color choices still persist.

**Additional context**
It doesn't even need to have a reset button, but any instructions on how to reset the color scheme back to the default ones would be good.

**Comment by robbporto** [comment]
That's exactly what I was looking for, @breandan: the default color scheme.

Feel free to close this issue.

Thank you very much.

Em seg., 22 de ago. de 2022 às 11:38, breandan ***@***.***>
escreveu:

**Comment by chylex** [comment]
I will commit a quality-of-life improvement for this shortly:

![obrazek](https://github.com/acejump/AceJump/assets/3685160/95f2a3cb-95cc-423a-8181-c3c56a2b5843)
