### ISSUE TITLE
AceJump doesn't work on nordic keyboard and preferences are not preserved on IDE restart

### ISSUE THREAD

**Issue by sebnil** [acejump/AceJump#416]
**Describe the bug**
When I reset the preferences of AceJump in AppCode I get:
0123456789abcdefghijklmnopqrstuvwxyzåäö

Having the "åäö" is ok since it's the keyboard I use. But the plugin doesn't work unless I remove åäö. 
When I save, the settings are reset on next AppCode start. So every day I have to change these settings to get AceJump to work

**To Reproduce**
1. Have a Swedish keyboard
2. Start AppCode and try to use Acejump. Doeesn't work.
3. Open settings. Remote åäö. OK.
4. Acejump work.s

**Expected behavior**
- Åäö should work.
- Saving preferences should work. 

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: macOS
 - AppCode 2022.2.4
 - AceJump version: 3.8.8

**Additional context**
NA

**Comment by breandan** [comment]
Have you tried the `Map unicode to ASCII` option under `File | Settings | Tools | AceJump | Language Settings`?

<img width="227" alt="Screenshot 2023-02-13 at 4 45 47 PM" src="https://user-images.githubusercontent.com/175716/218581791-0ed85d78-51e2-42b5-883d-94b78a5d2738.png">

It should map all characters to ASCII. I understand this is somewhat less than ideal for languages with diacritics.

I attempted to, but was unable to reproduce the issue you were describing with AppCode not saving the settings on restart. (macOS `13.1`/AceJump `3.8.11`/AppCode `2022.3.2`)
