### ISSUE TITLE
Doesn't work correctly with two files open side-by-side

### ISSUE THREAD

**Issue by ihor-oleks** [acejump/AceJump#417]
**Describe the bug**

When two tabs are opened side-by-side, AceJump ignores the right one

**To Reproduce**

1. Open two different files
2. Right click on the any tab and choose `Split and Move Right`
3. Trigger AceJump
4. Try to go to the tab on the right

**Expected behavior**

Ace Jump should work with split tabs correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/100670062/205898670-c47df90d-fcb5-416c-87e2-4eee9b30dac6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDE and version: 2022.3
 - AceJump version: 3.8.9

**Comment by lubomirfiala** [comment]
Can confirm this bug. It started happening after upgrade to phpstorm 2022.3  (macos 13.0.1)

**Comment by songkg7** [comment]
I have the exact same problem.

I will add information of device that I am using because it can be helpful in solving it.

OS: M1 Mac Ventura 13.0.1
IDE: IntelliJ IDEA 2022.3
AceJump version: 3.8.9

**Comment by mikravn** [comment]
Experiencing the same problem, the problem is really a deal-breaker if you always work with multiple tabs like me.

OS: Windows 11 22H2
IDE: IDEA 2022.3
AceJump version: 3.8.9

**Comment by mikravn** [comment]
I checked out the code and I think it is a minor regression after the latest update. 

It worked locally with my limited testing after this change:
https://github.com/acejump/AceJump/pull/423

**Comment by breandan** [comment]
Thank you for reporting this regression. A patch should be available to download in a few days, once approved by JetBrains.
