### ISSUE TITLE
Comments on this content 

### ISSUE THREAD

**Issue by Tan11Tan** [acejump/AceJump#419]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - IDE and version
 - AceJump version

**Additional context**

**Comment by Tan11Tan** [comment]
Hard to find some issue.please share your comments

**Comment by breandan** [comment]
Hi @Tan11Tan, why are you spamming our issue tracker with gibberish?

**Comment by Tan11Tan** [comment]
Hello: Breandan thanks for your comments and concerns i just starting to
learn I'm not doing well in this field.
Regards

Thanks


breandan ***@***.***> 於 2022年12月9日 週五 上午6:50 寫道：
