### ISSUE TITLE
Idea Plugin — TeamCity

### ISSUE THREAD

**Issue by Tan11Tan** [acejump/AceJump#424]
https://teamcity.jetbrains.com/buildConfiguration/JetBrainsPublicProjects_Compose_Publish_2_IdeaPlugin?mode=branches#all-projects

**Comment by breandan** [comment]
Dude… I would really like to know why you are spamming [so many issues](https://github.com/acejump/AceJump/issues?q=is%3Aissue+author%3ATan11Tan) on our issue tracker.
