### ISSUE TITLE
How to specify layer that I'm using?

### ISSUE THREAD

**Issue by goldlil** [acejump/AceJump#425]
I see in this files that we have support for colemak layer https://github.com/acejump/AceJump/blob/master/src/main/kotlin/org/acejump/input/KeyLayout.kt
How I can activate this layer in plugin?

**Comment by breandan** [comment]
Does navigating to `File | Settings | Tools | AceJump | Keyboard layout` and selecting `COLEMK` not work?

<img width="649" alt="Screenshot 2023-02-13 at 4 42 19 PM" src="https://user-images.githubusercontent.com/175716/218581346-3680fe3a-bf56-4a72-9cea-19c1cea1441c.png">

**Comment by goldlil** [comment]
Hi @breandan it does. Thanks!
