### ISSUE TITLE
Cycle order in settings plugin settings cannot be configured in Rider [2022.3.2]

### ISSUE THREAD

**Issue by amadare42** [acejump/AceJump#426]
**Describe the bug**
WHEN I open File | Settings | Tools | AceJump THEN "Modes / Cycle order:" block is uneditable and empty.
I would expect that I can use this field to configure modes order when cycling between them.

**To Reproduce**
1. Go to File | Settings | Tools | AceJump

**Expected behavior**
I would expect that I can use this field to configure modes order when cycling between them.

**Screenshots**
<img width="737" alt="image" src="https://user-images.githubusercontent.com/3945692/218550038-f7692fdc-a9e9-4a72-a876-ad7469ab6905.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Rider 2022.3.2
 - AceJump 3.8.10

**Comment by breandan** [comment]
Fix should be available in [`3.8.11`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/291897), thanks for reporting.
