### ISSUE TITLE
Hints are oval instead of square

### ISSUE THREAD

**Issue by stealzy** [acejump/AceJump#427]
**Describe the bug**
Oval round hints style make readability worse.

**Expected behavior**
Square hints.

**Screenshots**
<img src='https://s1.hostingkartinok.com/uploads/images/2023/03/955124fcaeba98d5fedc035ba686c831.png'/>

**Desktop (please complete the following information):**
 - OS: Windows
 - PyCharm 2019.3.3
 - AceJump 3.5.9

**Comment by breandan** [comment]
You are using a very old version of AceJump. Have you tried updating to the latest IDE and plug-in?

**Comment by stealzy** [comment]
Oh, I understand now, thanks.
On an outdated OS cannot install new IDE, on outdated IDE cannot install latest plug-in.

**Comment by breandan** [comment]
Hm, interesting. I assume you are on [Windows 7](https://intellij-support.jetbrains.com/hc/en-us/community/posts/4406429835922-What-is-the-latest-PyCharm-version-compatible-with-Windows-7-)? Although it would technically be possible to ship multiple distributions of the plugin to support older [IDEs and JVMs](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#intellij-platform-based-products-of-recent-ide-versions), supporting them becomes a more challenging commitment. PRs are certainly welcome, but I don't see us getting around to adding backwards compatibility anytime soon.

**Comment by stealzy** [comment]
Exactly. It's ok, not worth supporting.
