### ISSUE TITLE
Can't cycle through results using Enter

### ISSUE THREAD

**Issue by freddygv** [acejump/AceJump#429]
**Describe the bug**
Seems similar to #380 but Shift+Enter and Tab do work as expected.

**To Reproduce**
1. Activate AceJumpMode
1. Type something that matches several times
1. Press "Enter"
1. See error "File is read-only". Action has no results

**Expected behavior**
Should cycle through matches

**Desktop (please complete the following information):**
 - OS: Mac OS 12.6.4
 - GoLand 2023.1
 - AceJump 3.8.11

**Additional context**
Side note: is there a workaround where I could re-bind the behavior of Enter/Shift+Enter to be Tab/Shift+Tab? 

It seems like not according to #291

**Comment by breandan** [comment]
Thank you for reporting. This issue should now be fixed and released in version [`3.8.12`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/326497).
