### ISSUE TITLE
IntelliJ Idea AceJump Plugin doesn't work - java.lang.NoSuchFieldError: Companion 

### ISSUE THREAD

**Issue by neolee11** [acejump/AceJump#437]
**Describe the bug**

**To Reproduce**
I'm using Macbook M1
1. Install AceJump from IntelliJ marketplace
2. Use shortcut ctrl + ; to try to activate AceJump
3. Receive the java.lang.NoSuchFieldError: Companion error

**Expected behavior**
Activate AceJump

**Screenshots**
<img width="1282" alt="image" src="https://github.com/acejump/AceJump/assets/4872430/611183d3-fdcc-41d9-9b1d-24ab88808bcc">

**Desktop (please complete the following information):**
 - OS: MacOS
 - IDE and version: IntelliJ IDEA 2022.3.3 (Ultimate Edition)
 - AceJump version: 3.8.13

**Additional context**

**Comment by dmitriy-khokhlov** [comment]
I have the same problem.
OS: Windows 10
IDE and version: Rider 2022.3.3
AceJump version: 3.8.13

**Comment by breandan** [comment]
Hi @dmitriy-khokhlov, @neolee11, thank you for reporting. Could you please try updating to IntelliJ IDEA / Rider to version `2023.1+` and see if the issue is not fixed?

**Comment by ration** [comment]
At least on PHPStorm updating to 2023.1.2 resolved this issue.

**Comment by neolee11** [comment]
@breandan Yes, updating to 2023.1.2 worked for me. Thank you!
