### ISSUE TITLE
intellij idea ？？？

### ISSUE THREAD

**Issue by Hope2KZ** [acejump/AceJump#439]
![XI{)W}T7G3CHABQD%PF17EB](https://github.com/acejump/AceJump/assets/46066926/d91e1700-304d-4885-a73b-3c691cc22019)

**Comment by breandan** [comment]
@Hope2KZ 谢谢报告。 要不更新到 IntelliJ IDEA `2023.1+` 然后再试一次?

**Comment by wuruofan** [comment]
> ![XI{)W}T7G3CHABQD%PF17EB](https://user-images.githubusercontent.com/46066926/244851971-d91e1700-304d-4885-a73b-3c691cc22019.png)

I've done something to fix this bug, because I have to use the specific lower version idea ide.
You can try mine version.
https://github.com/acejump/AceJump/pull/440

我改了这个 bug，应该是低版本 idea 不兼容的问题，你可以试试看我这个版本行不，我这里 ok 了。


[AceJump.zip](https://github.com/acejump/AceJump/files/11729774/AceJump.zip)

**Comment by Hope2KZ** [comment]
> @Hope2KZ 谢谢报告。 要不更新到 IntelliJ IDEA `2023.1+` 然后再试一次?

thx

**Comment by Hope2KZ** [comment]
> > ![XI{)W}T7G3CHABQD%PF17EB](https://user-images.githubusercontent.com/46066926/244851971-d91e1700-304d-4885-a73b-3c691cc22019.png)
> 
> I've done something to fix this bug, because I have to use the specific lower version idea ide. You can try mine version. #440
> 
> 我改了这个 bug，应该是低版本 idea 不兼容的问题，你可以试试看我这个版本行不，我这里 ok 了。
> 
> [AceJump.zip](https://github.com/acejump/AceJump/files/11729774/AceJump.zip)

**Comment by Hope2KZ** [comment]
> > ![XI{)W}T7G3CHABQD%PF17EB](https://user-images.githubusercontent.com/46066926/244851971-d91e1700-304d-4885-a73b-3c691cc22019.png)
> 
> I've done something to fix this bug, because I have to use the specific lower version idea ide. You can try mine version. #440
> 
> 我改了这个 bug，应该是低版本 idea 不兼容的问题，你可以试试看我这个版本行不，我这里 ok 了。
> 
> [AceJump.zip](https://github.com/acejump/AceJump/files/11729774/AceJump.zip)
