### ISSUE TITLE
Doesn't work in WebStorm

### ISSUE THREAD

**Issue by YaroslavShilov** [acejump/AceJump#451]
Build #WS-223.8214.51, built on December 20, 2022
Windows 10 10.0

1. Plugins: 
![image](https://github.com/acejump/AceJump/assets/18420300/3b1ab864-63cc-499e-80b6-4ba10e6b97ee)

2. Add to .ideavimrc
![image](https://github.com/acejump/AceJump/assets/18420300/a8ec1b62-bc3e-461c-a302-26b916962cbb)

3. Reload webstorm, see error:
![image](https://github.com/acejump/AceJump/assets/18420300/0a0b13dc-0ef9-412b-9bb9-cdea8d1a3b6a)

**Comment by YaroslavShilov** [comment]
If I disable IdeaVim and IdeaVim-EasyMotion. AceJump shows me errors anyway

**Comment by breandan** [comment]
Thank you for reporting. Possibly related to [KT-56687](https://youtrack.jetbrains.com/issue/KT-56687/Unexpected-behaviour-with-enum-entries-when-using-outdated-stdlib) and the standard library changes from #450. It looks like Platform Plugin SDK 2023.3 [expects](https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#kotlin-standard-library) standard library version `1.9.10`. Just trying to parse this sentence:

> If a plugin supports [multiple platform versions](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html), it must either target the lowest bundled stdlib version or provide the specific version in plugin distribution.

Does this mean it is recommended to bundle an alternate stdlib or not? We are currently compiling with:

https://github.com/acejump/AceJump/blob/283c1a5644fd3d9d40de0f945cb4e1fffa9e24d6/build.gradle.kts#L6

With the guidance to disable disable stdlib bundling as per #449:

https://github.com/acejump/AceJump/blob/283c1a5644fd3d9d40de0f945cb4e1fffa9e24d6/gradle.properties#L1

@hsz is it possible to target `2023.3+` and build with `1.8.20` or there something we should be doing differently? Thanks.

**Comment by YaroslavShilov** [comment]
I updated Webstorm and now everything is working. It's my mistake

**Comment by breandan** [comment]
Sounds good. Please let us know if you encounter this issue again.
