### ISSUE TITLE
建议把说明文档里选择模式的部分放在醒目的地方

### ISSUE THREAD

**Issue by kazetyan** [acejump/AceJump#452]
> AceJump search is [smart case](http://ideavim.sourceforge.net/vim/usr_27.html#vim.27%2E1) sensitive, however tag selection is not case sensitive. Holding down `Shift`  when typing the last tag character will select all text from the current cursor position to that destination.

就是这行,之前一直没注意到,把代码clone到本地debug后才发现是有选择功能的
用习惯了emacsIDEAs,它的选择模式是单独触发的,惯性思维导致一直没找到acejump对应的功能
现在已经开始使用acejump,停不下来了,非常好用,还有unicode模式,中文用户非常受用,点赞!

**Comment by breandan** [comment]
谢谢您的评论，很高兴看到 AceJump 对您有用。如有功能需求或者改进意见，请随时提出，也欢迎提交PR！
