### ISSUE TITLE
Cannot use `ideavim` keybindings in the `target` mode while in `normal` mode (vim)

### ISSUE THREAD

**Issue by CestDiego** [acejump/AceJump#68]
Reproduction:
- Go into Normal mode in ideavim.
- Trigger AceJump, press `i` `p` or any other valid vim command that you want to go to. 

What to expect:
there should be popups in the code

What happens:
The action the keys are bound to is executed.

**Comment by breandan** [comment]
I could not reproduce this behavior with IdeaVim 0.46. Could you provide any further details on what version and IDE you are using? Thanks!

**Comment by tommyc38** [comment]
same thing happens to me...not sure how everyone else seems to be avoiding this issue?

**Comment by favetelinguis** [comment]
Im also having this problem. Nothing gets typed in the char search.

**Comment by breandan** [comment]
I am using IdeaVim 0.47 and do not have this problem on the latest version of AceJump and IntelliJ IDEA:

> IntelliJ IDEA 2016.3 EAP
> Build #IU-163.6512.17, built on October 19, 2016
> IntelliJ IDEA EAP User
> Expiration date: November 18, 2016
> JRE: 1.8.0_112-release-b403 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Could you post any additional information about your IDE and plugin versions?

**Comment by favetelinguis** [comment]
Here are my system details
Intellij IDA 2016.2.5 Community Ed
IdeaVim 0.47
MacOSX

**Comment by breandan** [comment]
Is this still an issue in the latest release?

**Comment by amosbird** [comment]
I also encountered this with latest ideavim and acejump

**Comment by breandan** [comment]
@amosbird Thanks for reporting. Which IDE and version?

**Comment by amosbird** [comment]
ideaj 2017.1.3

**Comment by breandan** [comment]
So just to make sure I'm getting this right:

1.) Activate AceJump Target mode.
2.) Type a character located in the editor, which is also bound to a Vim command.
3.) IdeaVim intercepts this key, AceJump does nothing.

Is my understanding correct? Two questions:

1.) What color is your caret before and after step #2?
2.) Does AceJump accept keys not bound in IdeaVim?

**Comment by amosbird** [comment]
>  1.) What color is your caret before and after step #2?


![](https://la.wentropy.com/edAD.png)


>  2.) Does AceJump accept keys not bound in IdeaVim?


Which keys can I try?

**Comment by breandan** [comment]
@amosbird Is that screenshot before or after step 2? Was the caret ever blue?

> Which keys can I try?

How about `;`?

**Comment by amosbird** [comment]
`;` doesn't do anything. I tested `f` `F` `g` and they all work although.

**Comment by breandan** [comment]
Possibly related: #128, #158.

**Comment by breandan** [comment]
I believe this should no longer be an issue as of `3.5.8`, otherwise please feel free to reopen.
